apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ghost-helm.fullname" . }}
  labels:
    {{- include "k8s-ghost-helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 2368
      protocol: TCP
  selector:
    {{- include "k8s-ghost-helm.selectorLabels" . | nindent 4 }}
